disk_keywords = [
    ("DIR", 0xCE),
    ("DRIVE", 0xCF),
    ("FIELD", 0xD0),
    ("FILES", 0xD1),
    ("KILL", 0xD2),
    ("LOAD", 0xD3),
    ("LSET", 0xD4),
    ("MERGE", 0xD5),
    ("RENAME", 0xD6),
    ("RSET", 0xD7),
    ("SAVE", 0xD8),
    ("WRITE", 0xD9),
    ("VERIFY", 0xDA),
    ("UNLOAD", 0xDB),
    ("DSKINI", 0xDC),
    ("BACKUP", 0xDD),
    ("COPY", 0xDE),
    ("DSKI$", 0xDF),
    ("DSKO$", 0xE0),
    ("DOS", 0xE1),
    ("CVN", 0xFFA2),
    ("FREE", 0xFFA3),
    ("LOC", 0xFFA4),
    ("LOF", 0xFFA5),
    ("MKN$", 0xFFA6),
    ("AS", 0xFFA7)
]
